# Generated by Django 3.2 on 2022-12-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='528746', max_length=255, null=True, verbose_name='Код подтверждения'),
        ),
    ]
